### PR TITLE
bad_access fix

### PR DESCRIPTION
**Pull request by hovox**

### CODE REVIEW

**Comment by Shadester** [comment]
This is needed! Thank you!

**Comment by Shadester** [comment]
Was this merged in, or is it not needed anymore?

**Comment by hovox** [comment]
merged

**Comment by hovox** [comment]
Why this was not merged? After last update I have experienced same crash.

**Comment by Kelcey** [comment]
Hello,

We've re-architected the MPNativeAd-adView relationship in our 4.0 release. This should not be a problem anymore.

If you see similar behavior in our latest release, please report it to the [MoPub Forum](https://twittercommunity.com/c/fabric/mopub).

Thanks!

**Pull request closed without merging**
